
#
# This is 1 of ZAWA's 10 habitat ranges. Each sub-range has its own list of biomes, and all of the sub-range's entities will spawn in those biomes.
# Disable entities (or a species variant) by setting "enabled" under their category to false.
# Use ONLY whole numbers greater than 0 for chance, min, and max!
# "chance" is how common they spawn, a higher number is more common than a lower number. "min" and "max" adjusts their spawning group size.
# !! If modded biomes are not generated, delete the entire "biomes" line for each sub-category and restart minecraft. !!
#
#
[inland_tundra]
	biomes = ["minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_mountains"]

[coastal_tundra]
	biomes = ["minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:snowy_beach", "minecraft:ice_spikes"]

	[coastal_tundra.emperor_penguin]
		enabled = true
		chance = 15
		min = 4
		max = 6

	[coastal_tundra.polar_bear]
		enabled = true
		chance = 5
		min = 1
		max = 1

