
#World generation related configuration
[World]
	#Controls the Patch Size [Default: 64]
	#Range: > 0
	gysahlGreenPatchSize = 64
	#Controls the Patch Rarity (Generating once every X tries) [Default: 2]
	#Range: > 1
	gysahlGreenRarity = 2
	#Controls the weight compared to other world gen [Default: true]
	gysahlGreensSpawnOnlyInOverworld = true

#Spawning configuration
[spawning]
	#Controls Chocobo Spawn Weight [Default: 10]
	#Range: > 0
	chocoboSpawnWeight = 10
	#Controls Chocobo Pack Size Min [Default: 1]
	#Range: > 0
	chocoboPackSizeMin = 1
	#Controls Chocobo Pack Size Max [Default: 3]
	#Range: > 0
	chocoboPackSizeMax = 5

#Chocobo configuration
[Chocobo]
	#This multiplier controls the tame chance per gysahl used, so .15 results in 15% chance to tame [Default: 0.15]
	#Range: 0.0 ~ 1.0
	tameChance = 0.15

#Naming configuration
[Naming]
	#If taming a chocobo will provide them with a name (unless already named) [Default: true]
	nameTamedChocobos = true
	#The list of male names it can choose from if 'nameTamedChocobos' is enabled
	maleNames =     [
						"Big Bird",             # Sesame Street
						"Daffy",                # Looney Tunes
						"Donald",               # Disney
						"Foghorn",              # Looney Tunes
						"Iago",                 # Aladdin
						"Johnathan",            # ... Livingston Seagull
						"Jose",                 # Unsure, Disney
						"Mordecai",             # Regular Show
						"Orville",              # Rescuers
						"Scrooge",              # Ducktales
						"Scuttle",              # The Little Mermaid
						"Woody"                 # Woodpecker
					]
		#The list of female names it can choose from if 'nameTamedChocobos' is enabled
	femaleNames   = [
						"Camilla",              # Muppets
						"Clara",                # Disney
						"Daisy",                # Disney
						"Flit",                 # Pocohontas
						"Goldie",               # Rock-a-Doodle
						"Magika De Spell",      # Ducktales
						"Shirley"               # Like, Tiny Toon Adventures
					]
