
["Recording Settings"]
	#It will be played endlessly. If enabled, the end and start points must be the same when recording.
	enableLoop = false

["Playback Settings"]
	#If enabled, a HUD displaying input states will be shown.
	showInputs = true

["Timeline Settings"]
	#The format of how time is displayed in Timeline Gui.
	timeStampFormat = "ticks"

["Menu Settings"]
	#If enabled, the server ip will be hidden.
	hiddenIp = true

