tier1:
    - "error"
tier2:
    - "doom:lost_soul"
tier3:
    - "doom:chaingunner"
    - "doom:pinky"
    - "doom:shotgunguy"
    - "doom:spectre"
tier4:
    - "doom:archvile"
    - "doom:baron"
    - "doom:cacodemon"
    - "doom:cyberdemon"
    - "doom:hellknight"
    - "doom:imp"
    - "doom:mancubus"
    - "doom:painelemental"
    - "doom:revenant"
    - "doom:spidermastermind"
tier5:
    - "error"