customRecipes: [] # none
unconsumedItems:
    # items which are not consumed by being in a crafting recipe
    # usually hammers, saws, philosopher's stone, etc
    # these items get omitted from the crafted item's EMC value
    - '<item:emendatusenigmatica:enigmatic_hammer>'
    - '<item:projecte:philosophers_stone>'
values:
    basemult: 311040
    # normal ones that are handed to the resolver
    # just like the config for ProjectE
    normal:
        base:
            -
                bep: '<item:emendatusenigmatica:copper_ingot>'
                value: 85
            -
                bep: '<item:emendatusenigmatica:lead_ingot>'
                value: 512
            -
                bep: '<item:emendatusenigmatica:uranium_ingot>'
                value: 4096
            -
                bep: '<item:mekanism:hdpe_pellet>'
                value: 0
            -
                bep: '<item:minecraft:chorus_fruit>'
                value: 192
            -
                bep: '<item:minecraft:coal>'
                value: 128
            -
                bep: '<item:minecraft:cobblestone>'
                value: 1
            -
                bep: '<item:minecraft:diamond>'
                value: 8192
            -
                bep: '<item:minecraft:ender_pearl>'
                value: 1024
            -
                bep: '<item:minecraft:flint>'
                value: 4
            -
                bep: '<item:minecraft:gold_ingot>'
                value: 2048
            -
                bep:  '<item:minecraft:iron_ingot>'
                value: 256
            -
                bep: '<item:minecraft:lapis_lazuli>'
                value: 864
            -
                bep:   '<item:minecraft:honeycomb>'
                value: 16
            -
                bep:   '<item:minecraft:oak_wood>'
                value: 32
            -
                bep:   '<item:minecraft:obsidian>'
                value: 64
            -
                bep:   '<item:minecraft:string>'
                value: 12
            -
                bep:    '<item:minecraft:sugar_cane>'
                value:  32
        derived:
            -
                bep:  '<item:minecraft:gold_nugget>'
                from: '<item:minecraft:gold_ingot>'
                type: 'division'
                value: 9
            -
                bep:  '<item:minecraft:iron_nugget>'
                from: '<item:minecraft:iron_ingot>'
                type: 'division'
                value: 9
        equivalent:
            -
                # base value 0
                bep: '<item:mekanism:hdpe_pellet>'
                children:
                    - '<item:appliedenergistics2:certus_quartz_crystal>'
                    - '<item:appliedenergistics2:fluix_crystal>'
                    - '<item:appliedenergistics2:purified_certus_quartz_crystal>'
                    - '<item:appliedenergistics2:purified_fluix_crystal>'
                    - '<item:botania:livingrock>'
                    - '<item:botania:livingwood>'
                    - '<item:doom:argent_energy>'
                    - '<item:doom:inmortalsphere>'
                    - '<item:doom:invisiblesphere>'
                    - '<item:doom:megasphere>'
                    - '<item:doom:powersphere>'
                    - '<item:emendatusenigmatica:certus_quartz_chunk>'
                    - '<item:emendatusenigmatica:charged_certus_quartz_chunk>'
                    - '<item:emendatusenigmatica:fluorite_chunk>'
                    - '<item:mekanism:fluorite_gem>'
                    - '<tag:items:forge:gems/fluorite>'
            -
                # items I chose to skip because they're unused
                bep: '<item:mekanism:hdpe_pellet>'
                children:
                    - '<item:emendatusenigmatica:apatite_chunk>'
                    - '<item:emendatusenigmatica:arcane_chunk>'
                    - '<item:emendatusenigmatica:cinnabar_chunk>'
                    - '<item:emendatusenigmatica:cobalt_chunk>'
                    - '<item:emendatusenigmatica:dimensional_chunk>'
                    - '<item:emendatusenigmatica:iridium_chunk>'
                    - '<item:emendatusenigmatica:potassium_nitrate_chunk>'
                    - '<item:emendatusenigmatica:sulfur_chunk>' # nah, you can use gunpowder and salt mate
            -
                # normally base value 1
                bep: '<item:minecraft:cobblestone>'
                children:
                    - '<item:atmospheric:arid_sand>'
                    - '<item:atmospheric:red_arid_sand>'
                    - '<item:minecraft:acacia_leaves>'
                    - '<item:minecraft:birch_leaves>'
                    - '<item:minecraft:dark_oak_leaves>'
                    - '<item:minecraft:dead_bush>'
                    - '<item:minecraft:dirt>'
                    - '<item:minecraft:fern>'
                    - '<item:minecraft:ice>'
                    - '<item:minecraft:jungle_leaves>'
                    - '<item:minecraft:oak_leaves>'
                    - '<item:minecraft:red_sand>'
                    - '<item:minecraft:sand>'
                    - '<item:minecraft:snow_block>'
                    - '<item:minecraft:spruce_leaves>'
                    - '<item:minecraft:stone>'
                    - '<item:quark:marble>'
                    - '<tag:items:forge:stone>'
                    - '<tag:items:minecraft:sand>'
                    # Tall Grass, Glass, Grass, Low Covalence Dust,
                    # Mycelium, Netherrack,
                    # Basalt, Basalt Brick, Basalt Cobblestone,
                    # Marble, Marble Brick, End Stone
            -
                # normally base value 12
                bep: '<item:minecraft:string>'
                children:
                    - '<item:environmental:yak_hair>'
                    - '<item:minecraft:cobweb>'
                    - '<tag:items:buzzier_bees:candle_wick>'
            -
                # normally base value 16
                bep: '<item:minecraft:honeycomb>'
                children:
                    - '<item:minecraft:lily_pad>'
                    - '<item:quark:tallow>'
                    - '<tag:items:buzzier_bees:candle_base>'
            -
                # normally 256/9 - 28.4 - probably not many of these
                bep: '<item:minecraft:iron_nugget>'
                children:
                    - '<tag:items:forge:nuggets/iron>'
                    - '<tag:items:forge:nuggets/tin>'
            -
                # normally base value 64
                bep: '<item:minecraft:obsidian>'
                children:
                    - '<item:chococraft:chocobo_drumstick_raw>'
                    - '<item:emendatusenigmatica:redstone_chunk>'
                    - '<item:fluxnetworks:flux_dust>'
                    - '<item:minecraft:beef>'
                    - '<item:minecraft:chicken>'
                    - '<item:minecraft:clay_ball>'
                    - '<item:minecraft:cod>'
                    - '<item:minecraft:leather>'
                    - '<item:minecraft:porkchop>'
                    - '<item:minecraft:pufferfish>'
                    - '<item:minecraft:redstone>'
                    - '<item:minecraft:salmon>'
                    - '<item:minecraft:tropical_fish>'
                    - '<item:zawa:angelfish>'
                    - '<item:zawa:clownfish>'
                    - '<item:zawa:large_meat>'
                    - '<item:zawa:medium_meat>'
                    - '<item:zawa:small_meat>'
                    - '<tag:items:forge:dusts/redstone>'
            -
                # normally base value 85
                bep: '<item:emendatusenigmatica:copper_ingot>'
                children:
                    - '<item:create:copper_ingot>'
                    - '<item:create:zinc_ingot>'
                    - '<item:emendatusenigmatica:aluminum_chunk>'
                    - '<item:emendatusenigmatica:copper_chunk>'
                    - '<item:emendatusenigmatica:zinc_chunk>'
                    - '<item:emendatusenigmatica:zinc_ingot>'
                    - '<item:mekanism:ingot_copper>'
                    - '<item:projectred-core:copper_ingot>'
                    - '<tag:items:forge:ingots/aluminum>'
                    - '<tag:items:forge:ingots/copper>'
                    - '<tag:items:forge:ingots/zinc>'
            -
                # normally base value 128
                bep: '<item:minecraft:coal>'
                children:
                    - '<item:emendatusenigmatica:coal_chunk>'
            -
                # normally base value 192
                bep: '<item:minecraft:chorus_fruit>'
                children:
                    - '<item:minecraft:saddle>'
                    - '<item:minecraft:gunpowder>'
            -
                # Normally base value 256
                bep: '<item:minecraft:iron_ingot>'
                children:
                    - '<item:emedatusenigmatica:tin_ingot>'
                    - '<item:emendatusenigmatica:bitumen_chunk>'
                    - '<item:emendatusenigmatica:iron_chunk>'
                    - '<item:emendatusenigmatica:quartz_chunk>'
                    - '<item:emendatusenigmatica:tin_chunk>'
                    - '<item:mapperbase:raw_bitumen>'
                    - '<item:mekanism:ingot_tin>'
                    - '<item:minecraft:quartz>'
                    - '<item:projectred-core:tin_ingot>'
                    - '<tag:items:forge:bitumen>'
                    - '<tag:items:forge:gems/quartz>'
                    - '<tag:items:forge:ingots/iron>'
                    - '<tag:items:forge:ingots/tin>'
            -
                # normally base value 512
                bep: '<item:emendatusenigmatica:lead_ingot>'
                children:
                    - '<item:emendatusenigmatica:lead_chunk>'
                    - '<item:emendatusenigmatica:osmium_chunk>'
                    - '<item:emendatusenigmatica:osmium_ingot>'
                    - '<item:emendatusenigmatica:silver_chunk>'
                    - '<item:emendatusenigmatica:silver_ingot>'
                    - '<item:mekanism:ingot_lead>'
                    - '<item:mekanism:ingot_osmium>'
                    - '<item:projectred-core:silver_ingot>'
                    - '<tag:items:forge:ingots/lead>'
                    - '<tag:items:forge:ingots/osmium>'
                    - '<tag:items:forge:ingots/silver>'
            -
                # normally base value 864
                bep: '<item:minecraft:lapis_lazuli>'
                children:
                    - '<item:emendatusenigmatica:lapis_chunk>'
                    - '<tag:items:forge:gems/lapis>'
            -
                # normally base value 1024
                bep: '<item:minecraft:ender_pearl>'
                children:
                    - '<item:emendatusenigmatica:emerald_chunk>'
                    - '<item:emendatusenigmatica:emerald_gem>'
                    - '<item:emendatusenigmatica:nickel_chunk>'
                    - '<item:emendatusenigmatica:nickel_ingot>'
                    - '<item:emendatusenigmatica:peridot_chunk>'
                    - '<item:emendatusenigmatica:peridot_gem>'
                    - '<item:emendatusenigmatica:ruby_chunk>'
                    - '<item:emendatusenigmatica:ruby_gem>'
                    - '<item:emendatusenigmatica:sapphire_chunk>'
                    - '<item:emendatusenigmatica:sapphire_gem>'
                    - '<item:minecraft:emerald>'
                    - '<item:projectred-core:peridot>'
                    - '<item:projectred-core:ruby>'
                    - '<item:projectred-core:sapphire>'
                    - '<tag:items:forge:ender_pearls>'
                    - '<tag:items:forge:gems/emerald>'
                    - '<tag:items:forge:gems/peridot>'
                    - '<tag:items:forge:gems/ruby>'
                    - '<tag:items:forge:gems/sapphire>'
                    - '<tag:items:forge:ingots/nickel>'
            -
                # Normally base value 2048
                bep: '<item:minecraft:gold_ingot>'
                children:
                    - '<item:emendatusenigmatica:gold_chunk>'
                    - '<tag:items:forge:ingots/gold>'
            -
                # normally base value 4096
                bep: '<item:emendatusenigmatica:uranium_ingot>'
                children:
                    - '<item:emendatusenigmatica:uranium_chunk>'
                    - '<item:mekanism:ingot_uranium>'
                    - '<item:minecraft:ghast_tear>'
                    - '<tag:items:forge:ingots/uranium>'
            -
                # normally base value 8192
                bep: '<item:minecraft:diamond>'
                children:
                    - '<item:emendatusenigmatica:diamond_chunk>'
                    - '<tag:items:forge:gems/diamond>'
            -
                # just woods
                bep: '<item:minecraft:oak_wood>'
                children:
                    - '<item:atmospheric:aspen_wood>'
                    - '<item:atmospheric:crustose_wood>'
                    - '<item:atmospheric:grimwood>'
                    - '<item:atmospheric:kousa_wood>'
                    - '<item:atmospheric:morado_wood>'
                    - '<item:atmospheric:rosewood>'
                    - '<item:atmospheric:watchful_aspen_wood>'
                    - '<item:atmospheric:yucca_wood>'
                    - '<item:autumnity:maple_wood>'
                    - '<item:autumnity:sappy_maple_wood>'
                    - '<item:environmental:cherry_wood>'
                    - '<item:environmental:willow_wood>'
                    - '<item:environmental:wisteria_wood>'
                    - '<item:minecraft:acacia_wood>'
                    - '<item:minecraft:birch_wood>'
                    - '<item:minecraft:crimson_hyphae>'
                    - '<item:minecraft:crimson_stem>'
                    - '<item:minecraft:dark_oak_wood>'
                    - '<item:minecraft:jungle_wood>'
                    - '<item:minecraft:spruce_wood>'
                    - '<item:minecraft:warped_hyphae>'
                    - '<item:minecraft:warped_stem>'
                    - '<tag:items:atmospheric:kousa_logs>'
                    - '<tag:items:atmospheric:morado_logs>'
                    - '<tag:items:autumnity:maple_logs>'
                    - '<tag:items:environmental:willow_logs>'
                    - '<tag:items:environmental:wisteria_logs>'
                    - '<tag:items:minecraft:birch_logs>'
                    - '<tag:items:minecraft:crimson_stems>'
                    - '<tag:items:minecraft:dark_oak_logs>'
                    - '<tag:items:minecraft:logs>'
                    - '<tag:items:minecraft:oak_logs>'
                    - '<tag:items:minecraft:spruce_logs>'
            -
                # late followup nonsense
                bep: '<item:minecraft:stick>'
                children:
                    - '<tag:items:forge:rods/wooden>'
    # late ones don't propagate
    # a way to tweak singular values after the fact
    late: [] # none