basemult: 4320 # this is documentation and not used by the program
customRecipes: [] # none
values:
    # normal ones that are handed to the resolver
    # just like the config for ProjectE
    normal:
        explicit:
            -
                bep: '<item:minecraft:coal>'
                value: 552960
            -
                bep: '<item:minecraft:cobblestone>'
                value: 4320
            -
                bep: '<item:minecraft:diamond>'
                value: 35389440
            -
                bep: '<item:minecraft:flint>'
                value: 17280
            -
                bep:   '<item:minecraft:oak_wood>'
                value: 276480
        equivalent:
            -
                bep: '<item:minecraft:cobblestone>'
                children:
                    - '<item:minecraft:acacia_leaves>'
                    - '<item:minecraft:birch_leaves>'
                    - '<item:minecraft:dark_oak_leaves>'
                    - '<item:minecraft:dead_bush>'
                    - '<item:minecraft:dirt>'
                    - '<item:minecraft:fern>'
                    - '<item:minecraft:ice>'
                    - '<item:minecraft:jungle_leaves>'
                    - '<item:minecraft:oak_leaves>'
                    - '<item:minecraft:sand>'
                    - '<item:minecraft:snow_block>'
                    - '<item:minecraft:spruce_leaves>'
                    - '<item:minecraft:stone>'
                    - '<item:quark:marble>'
                    # Tall Grass, Glass, Grass, Low Covalence Dust,
                    # Mycelium, Netherrack,
                    # Basalt, Basalt Brick, Basalt Cobblestone,
                    # Marble, Marble Brick, End Stone
            -
                bep: '<item:minecraft:oak_wood>'
                children:
                    - '<item:minecraft:burch_wood>'
                    - '<item:minecraft:spruce_wood>'
                    - '<item:minecraft:jungle_wood>'
                    - '<item:minecraft:acacia_wood>'
                    - '<item:minecraft:dark_oak_wood>'
    # late ones don't propagate
    # a way to tweak singular values after the fact
    late: [] # none