basemult: 6 # this is documentation and not used by the program
customRecipes: [] # none
values:
    # normal ones that are handed to the resolver
    # just like the config for ProjectE
    normal:
        explicit:
            -
                bep: '<item:minecraft:coal>'
                value: 768
            -
                bep: '<item:minecraft:diamond>'
                value: 49152
            -
                bep:   '<item:minecraft:oak_wood>'
                value: 384
        equivalent:
            -
                bep: '<item:minecraft:oak_wood>'
                children:
                    - '<item:minecraft:spruce_wood>'
                    - '<item:minecraft:jungle_wood>'
                    - '<item:minecraft:acacia_wood>'
                    - '<item:minecraft:dark_oak_wood>'
    # late ones don't propagate
    # a way to tweak singular values after the fact
    late: [] # none