basemult: 8640 # this is documentation and not used by the program
customRecipes: [] # none
unconsumedItems:
    # items which are not consumed by being in a crafting recipe
    # usually hammers, saws, philosopher's stone, etc
    # these items get omitted from the crafted item's EMC value
    - '<item:emendatusenigmatica:enigmatic_hammer>'
    - '<item:projecte:philosophers_stone>'
values:
    # normal ones that are handed to the resolver
    # just like the config for ProjectE
    normal:
        explicit:
            -
                bep: '<item:mekanism:hdpe_pellet>'
                value: 0
            -
                bep: '<item:minecraft:coal>'
                value: 4423680
            -
                bep: '<item:minecraft:cobblestone>'
                value: 34560
            -
                bep: '<item:minecraft:diamond>'
                value: 283115520
            -
                bep: '<item:minecraft:flint>'
                value: 138240
            -
                bep:   '<item:minecraft:iron_ingot>'
                value: 8847360
            -
                bep:   '<item:minecraft:oak_wood>'
                value: 2211840
            -
                bep:   '<item:minecraft:obsidian>'
                value: 2211840
            -
                bep:   '<item:minecraft:string>'
                value: 414720
        equivalent:
            -
                # base value 0
                bep: '<item:mekanism:hdpe_pellet>'
                children:
                    - 'botania:livingrock'
                    - 'botania:livingwood'
            -
                # normally base value 1
                bep: '<item:minecraft:cobblestone>'
                children:
                    - '<item:minecraft:acacia_leaves>'
                    - '<item:minecraft:birch_leaves>'
                    - '<item:minecraft:dark_oak_leaves>'
                    - '<item:minecraft:dead_bush>'
                    - '<item:minecraft:dirt>'
                    - '<item:minecraft:fern>'
                    - '<item:minecraft:ice>'
                    - '<item:minecraft:jungle_leaves>'
                    - '<item:minecraft:oak_leaves>'
                    - '<item:minecraft:sand>'
                    - '<item:minecraft:snow_block>'
                    - '<item:minecraft:spruce_leaves>'
                    - '<item:minecraft:stone>'
                    - '<item:quark:marble>'
                    - '<tag:items:forge:stone>'
                    # Tall Grass, Glass, Grass, Low Covalence Dust,
                    # Mycelium, Netherrack,
                    # Basalt, Basalt Brick, Basalt Cobblestone,
                    # Marble, Marble Brick, End Stone
            -
                # normally base value 12
                bep: '<item:minecraft:string>'
                children:
                    - '<item:minecraft:cobweb>'
            -
                # normally base value 64
                bep: '<item:minecraft:obsidian>'
                children:
                    - '<item:chococraft:chocobo_drumstick_raw>'
                    - '<item:minecraft:beef>'
                    - '<item:minecraft:chicken>'
                    - '<item:minecraft:clay_ball>'
                    - '<item:minecraft:cod>'
                    - '<item:minecraft:leather>'
                    - '<item:minecraft:porkchop>'
                    - '<item:minecraft:pufferfish>'
                    - '<item:minecraft:redstone>'
                    - '<item:minecraft:salmon>'
                    - '<item:minecraft:tropical_fish>'
                    - '<item:zawa:angelfish>'
                    - '<item:zawa:clownfish>'
                    - '<item:zawa:large_meat>'
                    - '<item:zawa:medium_meat>'
                    - '<item:zawa:small_meat>'
                    - '<tag:items:forge:dusts/redstone>'
            -
                # Normally base value 256
                bep: '<item:minecraft:iron_ingot>'
                children:
                    - '<item:emedatusenigmatica:tin_ingot>'
                    - '<item:mekanism:ingot_tin>'
                    - '<item:projectred-core:tin_ingot>'
                    - '<tag:items:forge:ingots/iron>'
                    - '<tag:items:forge:ingots/tin>'
            -
                # just woods
                bep: '<item:minecraft:oak_wood>'
                children:
                    - '<item:atmospheric:aspen_wood>'
                    - '<item:atmospheric:crustose_wood>'
                    - '<item:atmospheric:grimwood>'
                    - '<item:atmospheric:kousa_wood>'
                    - '<item:atmospheric:morado_wood>'
                    - '<item:atmospheric:rosewood>'
                    - '<item:atmospheric:watchful_aspen_wood>'
                    - '<item:atmospheric:yucca_wood>'
                    - '<item:autumnity:maple_wood>'
                    - '<item:autumnity:sappy_maple_wood>'
                    - '<item:environmental:cherry_wood>'
                    - '<item:environmental:willow_wood>'
                    - '<item:environmental:wisteria_wood>'
                    - '<item:minecraft:acacia_wood>'
                    - '<item:minecraft:birch_wood>'
                    - '<item:minecraft:crimson_hyphae>'
                    - '<item:minecraft:crimson_stem>'
                    - '<item:minecraft:dark_oak_wood>'
                    - '<item:minecraft:jungle_wood>'
                    - '<item:minecraft:spruce_wood>'
                    - '<item:minecraft:warped_hyphae>'
                    - '<item:minecraft:warped_stem>'
                    - '<tag:items:atmospheric:kousa_logs>'
                    - '<tag:items:atmospheric:morado_logs>'
                    - '<tag:items:autumnity:maple_logs>'
                    - '<tag:items:environmental:willow_logs>'
                    - '<tag:items:environmental:wisteria_logs>'
                    - '<tag:items:minecraft:birch_logs>'
                    - '<tag:items:minecraft:crimson_stems>'
                    - '<tag:items:minecraft:dark_oak_logs>'
                    - '<tag:items:minecraft:logs>'
                    - '<tag:items:minecraft:oak_logs>'
                    - '<tag:items:minecraft:spruce_logs>'
            -
                # late followup nonsense
                bep: '<item:minecraft:stick>'
                children:
                    - '<tag:items:forge:rods/wooden>'
    # late ones don't propagate
    # a way to tweak singular values after the fact
    late: [] # none